# If you come from bash you might have to change your $PATH.
 export PATH=$HOME/bin:/usr/local/bin:$PATH

 export PATH="$HOME/.dotfiles/scripts:$PATH"

 export PNPM_HOME="/home/alvamau5/.local/share/pnpm"
 export PATH="$PNPM_HOME:$PATH"

# Path to your oh-my-zsh installation.
#export ZSH="$HOME/.oh-my-zsh"

# Lang
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Git aliases
alias g='git'
alias ga='git add'
alias gc='git commit -v'
alias gd='git diff'
alias gf='git fetch'
alias glgg='git log --graph'
alias grmc='git rm --cached'
alias gst='git status'
alias gpm='git push'


# Aliases: tmux
alias ta='tmux attach'
alias tl='tmux list-sessions'
alias tm='tmux'

# System aliases
alias c='clear'
alias ..='cd ..'
alias ...='cd ../..'
alias del='rm -r'
alias b='bat'
alias ls='eza --icons --color=always'

# History configuration
HISTFILE=${HOME}/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY


#Yazi config
export EDITOR='nvim'
function y() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
  yazi "$@" --cwd-file="$tmp"
  IFS= read -r -d '' cwd < "$tmp"
  [ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
  rm -f -- "$tmp"
}

# Fzf aliases
alias inv='nvim $(fzf -m --preview="bat --color=always {}")'

# Set up fzf key bindings and fuzzy completion
if command -v fzf >/dev/null 2>&1; then
  source <(fzf --zsh)
fi

# GitHub Credentials
GITHUB_USERNAME=alvamau5

if [[ "$(uname)" == "Darwin" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
  test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

# Starship prompt
eval "$(starship init zsh)"

source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $(brew --prefix)/share/zsh-completions
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# opencode
export PATH=/home/alvamau5/.opencode/bin:$PATH
export PATH="$HOME/.local/bin:$PATH"

source /home/alvamau5/.config/broot/launcher/bash/br

autoload -U compinit
compinit

# Cargar el módulo zle (necesario para bindkey)
zmodload zsh/zle

bindkey -v

# Función corregida para cambiar de directorio al salir de Joshuto
joshutocd() {
    local tmp="$(mktemp)"
    
    # El argumento correcto es --output-file
    joshuto --output-file "$tmp" "$@"
    
    if [ -f "$tmp" ]; then
        local dir="$(cat "$tmp")"
        rm -f "$tmp"
        if [ -d "$dir" ] && [ "$dir" != "$(pwd)" ]; then
            cd "$dir"
        fi
    fi
}

# Mantener el alias activo
alias joshuto="joshutocd"
alias j="joshutocd"

# pnpm
export PNPM_HOME="/home/alvamau5/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME/bin:"*) ;;
  *) export PATH="$PNPM_HOME/bin:$PATH" ;;
esac
# pnpm end
